jobs:
  your_job_name_here:
    cloud_service_provider: GCP
    bucket_name: your_bucket_name
    path_to_remote_inputs: "path/to/some/dir/in/your/bucket"
    path_to_local_inputs: "path/to/save/inputs/on/disk"
    path_to_local_outputs: "path/to/save/outputs/on/disk"
    path_to_remote_outputs: "path/to/some/dir/in/your/bucket"
    steps:
      - "echo [path_to_local_inputs]"
      - "ls [path_to_local_inputs]"
      - "sh your_script.sh --input-dir [path_to_local_inputs] --output-dir [path_to_local_outputs]"
